- 名稱：上傳構建工件
  使用：actions/upload-artifact@v3.1.2
  和：
    # 工件名稱
    name: # 可選，默認為 artifact
    # 描述上傳內容的文件、目錄或通配符模式
    小路：
    # 如果使用提供的路徑找不到文件，則需要的行為。
可用選項：
  warn: 輸出警告但不要使操作失敗
  錯誤：操作失敗並顯示錯誤消息
  ignore：不輸出任何警告或錯誤，動作不失敗

    if-no-files-found: # 可選，默認為 warn
    # 神器將在幾天后過期的持續時間。0 表示使用默認保留。
至少 1 天。最多 90 天，除非從存儲庫設置頁面更改。

    保留天數：#可選
